lib/printf.c: making serial_printf return vsprintf ret value
Making it work the same way as current u-boot head, and as a side effect
also fixing build when -Werror=unused-but-set-variable is used:
printf.c: In function 'serial_printf':
printf.c:290:7: error: variable 'i' set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ricardo Salveti de Araujo <ricardo.salveti@linaro.org>
Signed-off-by: Anand Gadiyar <gadiyar@ti.com>